ArimaParameterList:
- n_lags
- n_forecasts
- ma
- i

DeepARParameterList:
- n_lags
- n_forecasts
- epochs
- learning_rate
- hidden_size
- rnn_layers

LSTMParameterList:
- n_lags
- n_forecasts
- num_hidden_layers
- d_hidden
- learning_rate
- epochs


NBeatsParameterList:
- n_lags
- n_forecasts
- epochs
- learning_rate

NPParameterList:
- n_lags
- n_forecasts
- learning_rate
- num_hidden_layers
- d_hidden
#- growth
#- changepoints
#- n_changepoints
#- changepoints_range
#- trend_reg
#- trend_reg_threshold
#- yearly_seasonality
#- weekly_seasonality
#- daily_seasonality
#- seasonality_mode
#- seasonality_reg
#- ar_sparsity
- learning_rate
- epochs
#- batch_size
#- loss_func
#- train_speed
#- normalize
#- impute_missing

SarimaParameterList:
- n_lags
- n_forecasts
- ma
- i
- seasonal

SklearnParameterList:
- random_state
- n_lags
- n_forecasts

TFTParameterList:
- n_lags
- n_forecasts
- epochs
- attention_head_size
- hidden_continuous_size
- hidden_size

ProphetParameterList:
- n_forecasts
- n_lags

attention_head_size:
- 1
- 8
d_hidden:
- 8
- 16
epochs:
- 10
- 40
- 100

fold_overlap_pct: 0.05

hidden_continuous_size:
- 8

hidden_size:
- 8
- 16

i:
- 1

k: 5

learning_rate:
- 0.001
- 0.01
- 0.1

ma:
- 3

method: NP

n_forecasts:
- 1
- 6
- 24

n_lags:
- 12
- 24
- 72

num_hidden_layers:
- 1
- 4

#parameter_list: DeepARParameterList

#preprocessing_type: NP

random_state:
- 42

rnn_layers:
- 2

seasonal:
- 24

test_proportion: 0.05





AirQualityUCI:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
BeijingPM25:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
DailyDemandForecastingOrders:
  freq: D
  n_forecasts:
  - 1
  - 7
  - 21
  n_lags:
  - 0
  - 1
  - 7
  - 21
  - 60
  nan_interpolation: zero
ERCOTDAM:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
EnergyData:
  freq: 10min
  n_forecasts:
  - 1
  - 12
  - 72
  n_lags:
  - 0
  - 1
  - 24
  - 72
  - 144
  nan_interpolation: linear
FiveCitiesPMData_Beijing:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
FiveCitiesPMData_Chengdu:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
FiveCitiesPMData_Guangzhou:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
FiveCitiesPMData_Shanghai:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
FiveCitiesPMData_Shenyang:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
LondonDataStore:
  freq: D
  n_forecasts:
  - 1
  - 7
  - 21
  n_lags:
  - 0
  - 1
  - 7
  - 21
  - 60
  nan_interpolation: zero
MetroInterstateTrafficVolume:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Aotizhongxin:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Changping:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Dingling:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Dongsi:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Guanyuan:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Gucheng:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Huairou:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Nongzhanguan:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Shunyi:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Tiantan:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Wanliu:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
PRSA_Wanshouxigong:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
Parking_Birmingham_BHMBCCMKT01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBCCPST01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBCCSNH01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBCCTHL01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBRCBRG01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBRCBRG02:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBRCBRG03:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMBRTARC01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMEURBRD01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMEURBRD02:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMMBMMBX01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMNCPHST01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMNCPLDH01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMNCPNHS01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMNCPNST01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMNCPPLS01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_BHMNCPRAN01:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Broad Street:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Bull Ring:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_NIA Car Parks:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_NIA North:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_NIA South:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS105a:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS119a:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS133:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS135a:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS202:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS8:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Others-CCCPS98:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
Parking_Birmingham_Shopping:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero
RTEConsumption:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
RaleighPV:
  freq: H
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 24
  - 96
  nan_interpolation: linear
TrafficBrazil:
  freq: 30min
  n_forecasts:
  - 1
  - 12
  - 48
  n_lags:
  - 0
  - 1
  - 12
  - 48
  - 96
  nan_interpolation: zero

constant:
  freq: 1H
  nan_interpolation: linear
electricity:
  freq: 1H
  nan_interpolation: linear
electricity_nips:
  freq: H
  nan_interpolation: linear
exchange_rate:
  freq: 1B
  nan_interpolation: linear
exchange_rate_nips:
  freq: B
  nan_interpolation: linear
m1_monthly:
  freq: M
  nan_interpolation: linear
m1_quarterly:
  freq: Q
  nan_interpolation: linear
m1_yearly:
  freq: Y
  nan_interpolation: linear
m3_monthly:
  freq: M
  nan_interpolation: linear
m3_other:
  freq: Q
  nan_interpolation: linear
m3_quarterly:
  freq: Q
  nan_interpolation: linear
m3_yearly:
  freq: Y
  nan_interpolation: linear
m4_daily:
  freq: D
  nan_interpolation: linear
m4_hourly:
  freq: H
  nan_interpolation: linear
m4_weekly:
  freq: W
  nan_interpolation: linear
nn5_daily_with_missing:
  freq: D
  nan_interpolation: linear
nn5_daily_without_missing:
  freq: D
  nan_interpolation: linear
nn5_weekly:
  freq: W
  nan_interpolation: linear
solar-energy:
  freq: 1H
  nan_interpolation: linear
solar_nips:
  freq: H
  nan_interpolation: linear
test:
  freq: H
  nan_interpolation: linear
tourism_monthly:
  freq: M
  nan_interpolation: linear
tourism_quarterly:
  freq: Q
  nan_interpolation: linear
tourism_yearly:
  freq: Y
  nan_interpolation: linear
traffic:
  freq: H
  nan_interpolation: linear
traffic_nips:
  freq: H
  nan_interpolation: linear
